-- ============================================================
--  CropCare / Pesticide & Fertilizer Inventory Management
--  MySQL Database Schema + Seed Data
-- ============================================================

CREATE DATABASE IF NOT EXISTS pesticide_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pesticide_db;

CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    company_name VARCHAR(150) DEFAULT 'My Corporation',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- NOTE: the default admin account (admin@pesticide.com / admin123) is
-- created automatically the first time the app runs (see config/database.php),
-- so the password hash is generated by your own PHP install and is guaranteed
-- to work. No need to insert it manually here.

-- ------------------------------------------------------------
-- Categories (predefined + custom, as required)
-- ------------------------------------------------------------
CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    type ENUM('default','custom') NOT NULL DEFAULT 'custom',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name, type) VALUES
('Fertilizers', 'default'),
('Sprays', 'default'),
('Seeds', 'default'),
('Insecticides', 'default'),
('Pesticides', 'default');

-- ------------------------------------------------------------
-- Subcategories
-- ------------------------------------------------------------
CREATE TABLE subcategories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

INSERT INTO subcategories (category_id, name) VALUES
(1, 'Nitrogenous Fertilizers'),
(1, 'Phosphate Fertilizers'),
(1, 'Organic Manure'),
(2, 'Fungicide Spray'),
(2, 'Weedicide Spray'),
(3, 'Hybrid Seeds'),
(3, 'Crop Seeds'),
(4, 'Liquid Insecticide'),
(4, 'Powder Insecticide'),
(5, 'Systemic Pesticide');


-- ------------------------------------------------------------
-- Products
-- ------------------------------------------------------------
CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(50) DEFAULT NULL,
    category_id INT NOT NULL,
    unit ENUM('kg','g','liter','ml','bag','pcs') NOT NULL DEFAULT 'kg',
    purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    selling_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
    low_stock_threshold DECIMAL(12,2) NOT NULL DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);

INSERT INTO products (name, sku, category_id, unit, purchase_price, selling_price, quantity, low_stock_threshold) VALUES
('Urea 46%', 'UR-001', 2, 'kg', 1200.00, 1400.00, 46, 20),
('DAP Fertilizer', 'DAP-001', 2, 'bag', 8500.00, 9200.00, 30, 10),
('Khadd (Organic Manure)', 'KH-001', 4, 'kg', 563.00, 573.00, 15, 20),
('Confidor Spray', 'SP-001', 3, 'liter', 1450.00, 1750.00, 8, 10),
('Roundup Weedicide', 'SP-002', 3, 'liter', 980.00, 1250.00, 25, 10),
('Corn Seeds Hybrid', 'SD-001', 4, 'kg', 350.00, 420.00, 60, 15),
('Cypermethrin Insecticide', 'IN-001', 5, 'liter', 700.00, 890.00, 5, 10);

-- ------------------------------------------------------------
-- Sales
-- ------------------------------------------------------------
CREATE TABLE sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL,
    price_per_unit DECIMAL(12,2) NOT NULL,
    total DECIMAL(14,2) NOT NULL,
    sale_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

INSERT INTO sales (product_id, customer_name, quantity, price_per_unit, total, sale_date) VALUES
(1, 'Hamza', 35, 670.00, 23450.00, CURDATE()),
(3, 'Umer', 9, 1600.00, 14400.00, CURDATE()),
(4, 'Ali Ashraf', 1, 1500.00, 1500.00, CURDATE());

-- ------------------------------------------------------------
-- Purchases
-- ------------------------------------------------------------
CREATE TABLE purchases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    supplier_name VARCHAR(150) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL,
    price_per_unit DECIMAL(12,2) NOT NULL,
    total DECIMAL(14,2) NOT NULL,
    purchase_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

INSERT INTO purchases (product_id, supplier_name, quantity, price_per_unit, total, purchase_date) VALUES
(1, 'Shafqat', 10, 1200.00, 12000.00, CURDATE());
